# {{WORKFLOW_NAME}} - GitHub Actions Workflow
#
# Template Placeholders:
# - {{WORKFLOW_NAME}}: Workflow display name
# - {{TRIGGER_BRANCH}}: Branch to trigger on (e.g., main, develop)
# - {{NODE_VERSION}}: Node.js version (e.g., 20)
# - {{PACKAGE_MANAGER}}: npm, yarn, or pnpm
#
# Usage: Copy this template and customize for your project

name: {{WORKFLOW_NAME}}

on:
  push:
    branches: [{{TRIGGER_BRANCH}}]
  pull_request:
    branches: [{{TRIGGER_BRANCH}}]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "{{NODE_VERSION}}"
  # Add environment variables here
  # API_URL: ${{ secrets.API_URL }}

jobs:
  # =============================================================================
  # Lint & Type Check
  # =============================================================================
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "{{PACKAGE_MANAGER}}"

      - name: Install dependencies
        run: {{PACKAGE_MANAGER}} install --frozen-lockfile

      - name: Run linter
        run: {{PACKAGE_MANAGER}} run lint

      - name: Run type check
        run: {{PACKAGE_MANAGER}} run type-check

  # =============================================================================
  # Unit Tests
  # =============================================================================
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "{{PACKAGE_MANAGER}}"

      - name: Install dependencies
        run: {{PACKAGE_MANAGER}} install --frozen-lockfile

      - name: Run tests
        run: {{PACKAGE_MANAGER}} test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  # =============================================================================
  # Build
  # =============================================================================
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "{{PACKAGE_MANAGER}}"

      - name: Install dependencies
        run: {{PACKAGE_MANAGER}} install --frozen-lockfile

      - name: Build application
        run: {{PACKAGE_MANAGER}} run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 7

  # =============================================================================
  # E2E Tests (Optional)
  # =============================================================================
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "{{PACKAGE_MANAGER}}"

      - name: Install dependencies
        run: {{PACKAGE_MANAGER}} install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      - name: Run E2E tests
        run: {{PACKAGE_MANAGER}} run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  # =============================================================================
  # Security Scan
  # =============================================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "{{PACKAGE_MANAGER}}"

      - name: Install dependencies
        run: {{PACKAGE_MANAGER}} install --frozen-lockfile

      - name: Run security audit
        run: {{PACKAGE_MANAGER}} audit --audit-level=high
        continue-on-error: true

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # =============================================================================
  # Deploy (Production)
  # =============================================================================
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/{{TRIGGER_BRANCH}}' && github.event_name == 'push'
    environment:
      name: production
      url: https://{{PRODUCTION_URL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      # Add your deployment steps here
      # Example: Vercel deployment
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: ./

      # Example: Notify on Slack
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
